Description: Mobile Applications Lite
Name: mobile-applications-lite
Packages:
##TODO: Reenable after all packages build
#- org.tizen.app-selector
#- org.tizen.bt-syspopup
##- org.tizen.browser
- org.tizen.calculator
#- org.tizen.calendar
#- org.tizen.calendar-viewer
#- org.tizen.call
#- org.tizen.camera-app
#- org.tizen.clock
#- org.tizen.contacts
#- org.tizen.contacts-viewer
#- org.tizen.email
#- org.tizen.gallery
#- org.tizen.image-viewer
- org.tizen.indicator
#- org.tizen.lockscreen
#- org.tizen.lowbat-syspopup
#- org.tizen.lowmem-syspopup
#- org.tizen.memo
- org.tizen.menu-screen
#- org.tizen.message
#- org.tizen.music-player
#- org.tizen.myfile
#- org.tizen.net-popup
#- org.tizen.phone
#- org.tizen.poweroff-syspopup
#- org.tizen.pwlock
#- org.tizen.quickpanel
#- org.tizen.setting
#- org.tizen.smartsearch
#- org.tizen.taskmgr
#- org.tizen.usb-syspopup
#- org.tizen.video-player
#- org.tizen.volume
#- org.tizen.wifi-direct-popup
#- org.tizen.wifi-direct-ugapp
Summary: Mobile Applications Lite
