Summary: Wearable Applications
Description: Wearable Applications
Name: wearable-applications
Packages:
- ail
- ca-certificates
- push-bin
- libpush
- boot-animation
- starter
- app-installers
- data-provider-master
- tpk-backend
- wgt-backend
- libwidget_service
- libwidget_viewer
- libwidget_viewer_evas
- org.tizen.heremaps-uc
- org.tizen.idle-clock-digital
- org.tizen.w-home
- org.tizen.watch-setting
- org.tizen.elm-demo-tizen-wearable
