Summary: Wearable Applications
Description: Wearable Applications
Name: wearable-applications
Packages:
- ail
- ca-certificates
- push-bin
- libpush
- boot-animation
- starter
- app-installers
- data-provider-master
- tpk-backend
- wgt-backend
- libwidget_service
- libwidget_viewer
- libwidget_viewer_evas
